; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Patroni Environment Setup"
#define MyAppInstallDir "PES"
#define MyAppVersion "v240516"
#define MyAppPublisher "CYBERTEC PostgreSQL International GmbH"
#define MyAppURL "https://www.cybertec-postgresql.com/"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{4D29D928-999E-4D56-9896-76DEB4F259EC}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={sd}\{#MyAppInstallDir}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=..\LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only.)
; PrivilegesRequired=lowest
OutputDir=..
OutputBaseFilename=Patroni-Env-Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode="x64"
AppCopyright=CYBERTEC PostgreSQL International GmbH

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: "..\PES\*"; DestDir: "{app}"; Flags: ignoreversion createallsubdirs recursesubdirs

[Icons]
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

[Run]
Filename: "pwsh.exe"; Parameters: "-ExecutionPolicy Bypass -File ""{app}\install.ps1"""; WorkingDir: "{app}"; Flags: waituntilterminated

[UninstallRun]
Filename: "pwsh.exe"; Parameters: "-ExecutionPolicy Bypass -File ""{app}\uninstall.ps1"""; WorkingDir: "{app}"; Flags: waituntilterminated




[Code]
{ install.ps1 and uninstall.ps1 both declare "#Requires -Version 7.0". Windows
  PowerShell 5.1 (powershell.exe) refuses to run them, so the setup must launch
  pwsh.exe and must not proceed at all when PowerShell 7 is missing. }
function PwshPresent(): Boolean;
var
  ResultCode: Integer;
begin
  Result := Exec('pwsh.exe', '-NoProfile -Command "exit 0"', '', SW_HIDE,
                 ewWaitUntilTerminated, ResultCode) and (ResultCode = 0);
end;

function InitializeSetup(): Boolean;
begin
  Result := PwshPresent();
  if not Result then
    MsgBox('PowerShell 7 (pwsh.exe) was not found on this machine.' #13#10#13#10
           'The Patroni Environment Setup scripts require PowerShell 7 or newer.' #13#10
           'Install it from https://aka.ms/powershell and run this setup again.',
           mbCriticalError, MB_OK);
end;
